CREATE TABLE users (
	id serial PRIMARY KEY,
	email VARCHAR ( 200 ) UNIQUE NOT NULL,
	password VARCHAR ( 50 ) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE, 
    created_at TIMESTAMP DEFAULT now()
);